server:
  port: 8080

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password : 0837333

spring:
  datasource:
    url: ENC(GRU193kDXTw/UC3u/SOe3iJ1+F5O3kNs0muV3QMonyDEfR9jqPalEgJzKVVnbEv7+jy1XyHdTJdlQGBbRdPWpNnu6kn+H1tn4+QSE00H6OYudzWdJkBJJNGNSd8PPwrjteAqUuWwCg+zXa2wACv4tLLadeLq8FdMys0G2na+R3HCa/iwFUz41uVGxceFD4VXOL+gwV3Qlk6YrriM1VK5LYEPtD3+PyLGoqBeAt47Xx2Bj7pNLY4ZGQ==)
#    url: jdbc:mysql://127.0.0.1:3306/tamlain?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(F301hhYYYd0rvHquA7NOgA==)
    password: ENC(rqkqAtx5oXQkJdp8OtsRZQ==)
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
        check_nullability: true
  redis:
    host: localhost
    port: 6379

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ENC(pspsCp49iwIKXZSfdz59qYd1AWOrsKMbrPKjLEtPp3FjTKLSC5sdLSAS0fOLgi9/)
#            redirect-uri: http://localhost:8080/oauth/callback/kakao
#            redirect-uri: http://localhost:3000/oauth/callback/kakao
            redirect-uri: ENC(gR5YHZ7AwDZ13S8Sl/pfv+Fa7r9xtdwnzaaFZr3m9ZxNkEv4PkRl5rZQkRwPHBcBZ0cVE6/4ulk=)
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
            client_name: kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  token:
    secret-key: ENC(kaKqOrrX5YmcpNoH4rOlq4BIhQobzfPfpHLB4SlHnnR68EuLOxCBZ888oMXgeCH8wFuf/Z6uP/4aA/YAMUKc7fqNG99RdBxcOIqYuaHvXGNDaQDCxsuN/Hng8djDZ44wFjcnpf8JYztW1dZSpzuQkRHeoGV45359RVR6PKy0bL6oun3O+eDBKmMRQyEP+y0w)
  access-token:
    expire-length: 1800000
  refresh-token:
    expire-length: 1209600000